<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<Authors>IceCoffee</Authors>
		<Company>LuoShuiTianYi</Company>
		<Copyright>Copyright (c) 2026 IceCoffee</Copyright>
		<Description>A simple AspNetCore web api library.</Description>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/IceCoffee1024/IceCoffee.AspNetCore</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<RepositoryUrl>https://github.com/IceCoffee1024/IceCoffee.AspNetCore</RepositoryUrl>
		<Version>2.0.0</Version>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="IceCoffee.Common" Version="1.5.1" />
		<PackageReference Include="FastExpressionCompiler" Version="5.4.1" />
		<PackageReference Include="idunno.Authentication.Basic" Version="2.4.0" />
		<PackageReference Include="Mapster" Version="10.0.7" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.File.Archive" Version="1.0.6" />
		<PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE" Pack="true" PackagePath="" Visible="false" />
		<None Include="..\..\README.md" Pack="true" PackagePath="" Visible="false" />
	</ItemGroup>

</Project>
